artifact_uri: ./mlruns/0/0cd7c01d0b1c4d3aba943d2826bbccb6/artifacts
end_time: 1578261531439
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 0cd7c01d0b1c4d3aba943d2826bbccb6
run_uuid: 0cd7c01d0b1c4d3aba943d2826bbccb6
source_name: ''
source_type: 4
source_version: ''
start_time: 1578261531336
status: 4
tags: []
user_id: Felipe
